when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
        options:
            traces_sample_rate: 0.05
            ignore_exceptions:
                - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'